baseurl = "https://holdren.ca"
DefaultContentLanguage = "en"
title = "Ryan Holdren"
theme = "beautifulhugo"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[Params]
  homeTitle = "Ryan Holdren"
  subtitle = "Here be blog"
  mainSections = ["post","posts"]
  logo = "img/avatar-icon.png"
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = false
  readingTime = false
  since = "2025"
  wordCount = false
  useHLJS = true
  socialShare = false
  delayDisqus = false
  showRelatedPosts = false

[Params.author]
  name = "Ryan Holdren"
  website = "holdren.ca"
  email = "ryan@holdren.ca"

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [["\\[","\\]"], ["$$","$$"]]
          inline = [["\\(","\\)"]]